### ISSUE TITLE
Remover Vercel e GithubPages do projeto

### ISSUE THREAD

**Issue by FelJohnny** [otaviosouza21/sat-webpage-front#8]
Visto que ja utilizamos servidores na aws, sugiro que remova esses actions

não tenho acesso para remover

**Comment by otaviosouza21** [comment]
Vercel e gitpages removidos do repositorio

![image](https://github.com/otaviosouza21/sat-webpage-front/assets/112784103/f7cdb9c5-f4fc-4c2a-9027-83b5f74ea322)
